In [10]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
data = pd.read_csv("groceries - groceries.csv")
data.head(3)

,Item(s),Item 1,Item 2,Item 3,Item 4,Item 5,Item 6,Item 7,Item 8,Item 9,...,Item 23,Item 24,Item 25,Item 26,Item 27,Item 28,Item 29,Item 30,Item 31,Item 32
0,4,citrus fruit,semi-finished bread,margarine,ready soups,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,3,tropical fruit,yogurt,coffee,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,whole milk,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
data.shape

(9835, 33)

In [13]:
data.columns

Index(['Item(s)', 'Item 1', 'Item 2', 'Item 3', 'Item 4', 'Item 5', 'Item 6',
       'Item 7', 'Item 8', 'Item 9', 'Item 10', 'Item 11', 'Item 12',
       'Item 13', 'Item 14', 'Item 15', 'Item 16', 'Item 17', 'Item 18',
       'Item 19', 'Item 20', 'Item 21', 'Item 22', 'Item 23', 'Item 24',
       'Item 25', 'Item 26', 'Item 27', 'Item 28', 'Item 29', 'Item 30',
       'Item 31', 'Item 32'],
      dtype='str')

In [14]:
market = []
for i in range(0,data.shape[0]):
    cust = []
    for j in data.columns :
        if type(data[j][i])==str:
            cust.append(data[j][i])

    market.append(cust)

In [16]:
l = []
for i in market:
    for j in i :
        l.append(j)

In [20]:
import collections
p = collections.Counter(l)

In [23]:
d = {"Item Name":p.keys(),"values":p.values()}
pd.DataFrame(d).sort_values(by=["values"],ascending=False)

                 Item Name  values
7               whole milk    2513
11        other vegetables    1903
17              rolls/buns    1809
31                    soda    1715
5                   yogurt    1372
..                     ...     ...
164                   bags       4
167        kitchen utensil       4
168  preservation products       2
159              baby food       1
166   sound storage medium       1

[169 rows x 2 columns]

In [27]:
from mlxtend.preprocessing.transactionencoder import TransactionEncoder
tr = TransactionEncoder()
tr.fit(market)

C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:383: UserWarning: potentially wrong underline length...
Parameters
------------ in
Encoder class for transaction data in Python lists
...
  if not self._is_at_section():
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Attributes
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():
C:\Users\ASUS\anaconda3\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:203: UserWarning: potentially wrong underline length...
Examples
------------ in
Encoder class for transaction data in Python lists
...
  while not self._is_at_section() and not self._doc.eof():

TransactionEncoder()

In [30]:
df = pd.DataFrame(tr.transform(market),columns=tr.columns_)
df

,Instant food products,UHT-milk,abrasive cleaner,artif. sweetener,baby cosmetics,baby food,bags,baking powder,bathroom cleaner,beef,...,turkey,vinegar,waffles,whipped/sour cream,whisky,white bread,white wine,whole milk,yogurt,zwieback
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9830,False,False,False,False,False,False,False,False,False,True,...,False,False,False,True,False,False,False,True,False,False
9831,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9832,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
9833,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
9834,False,False,False,False,False,False,False,False,False,False,...,False,True,False,False,False,False,False,False,False,False

In [33]:
from mlxtend.frequent_patterns import apriori
ap = apriori(df,min_support=0.05,use_colnames=True,max_len=3)
ap.sort_values(by=["support"])

     support                                   itemsets
13  0.052364                       frozenset({napkins})
0   0.052466                          frozenset({beef})
8   0.053279                          frozenset({curd})
4   0.055414                        frozenset({butter})
30  0.056024            frozenset({yogurt, whole milk})
29  0.056634        frozenset({rolls/buns, whole milk})
18  0.057651                          frozenset({pork})
7   0.058058                        frozenset({coffee})
12  0.058566                     frozenset({margarine})
10  0.058973                   frozenset({frankfurter})
9   0.063447                 frozenset({domestic eggs})
3   0.064870                   frozenset({brown bread})
25  0.071683            frozenset({whipped/sour cream})
11  0.072293         frozenset({fruit/vegetable juice})
28  0.074835  frozenset({other vegetables, whole milk})
17  0.075648                     frozenset({pip fruit})
5   0.077682                   frozenset({canned beer})
14  0.079817                    frozenset({newspapers})
1   0.080529                  frozenset({bottled beer})
6   0.082766                  frozenset({citrus fruit})
16  0.088968                        frozenset({pastry})
21  0.093950                       frozenset({sausage})
22  0.098526                 frozenset({shopping bags})
24  0.104931                frozenset({tropical fruit})
20  0.108998               frozenset({root vegetables})
2   0.110524                 frozenset({bottled water})
27  0.139502                        frozenset({yogurt})
23  0.174377                          frozenset({soda})
19  0.183935                    frozenset({rolls/buns})
15  0.193493              frozenset({other vegetables})
26  0.255516                    frozenset({whole milk})